class NigerianStatesCities {
  static const List<String> states = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'FCT (Abuja)',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
  ];

  static const Map<String, List<String>> stateToCities = {
    'Abia': [
      'Aba',
      'Umuahia',
      'Ohafia',
      'Arochukwu',
      'Bende',
      'Osisioma',
      'Isiala Ngwa',
      'Ugwunagbo',
      'Ukwa',
      'Other Area',
    ],
    'Adamawa': [
      'Yola (Capital)',
      'Jimeta',
      'Mubi',
      'Numan',
      'Ganye',
      'Michika',
      'Mayo Belwa',
      'Other Area',
    ],
    'Akwa Ibom': [
      'Uyo (Capital)',
      'Eket',
      'Ikot Ekpene',
      'Oron',
      'Ikot Abasi',
      'Abak',
      'Etinan',
      'Ibiono Ibom',
      'Other Area',
    ],
    'Anambra': [
      'Awka (Capital & GRA)',
      'Onitsha',
      'Nnewi',
      'Ekwulobia',
      'Ihiala',
      'Ogbaru',
      'Agulu',
      'Obosi',
      'Nkpor',
      'Other Area',
    ],
    'Bauchi': [
      'Bauchi (Capital)',
      'Azare',
      'Misau',
      'Jama\'are',
      'Katagum',
      'Ningi',
      'Tafawa Balewa',
      'Other Area',
    ],
    'Bayelsa': [
      'Yenagoa (Capital)',
      'Brass',
      'Ogbia',
      'Sagbama',
      'Nembe',
      'Amassoma',
      'Kolokuma/Opokuma',
      'Other Area',
    ],
    'Benue': [
      'Makurdi (Capital)',
      'Gboko',
      'Otukpo',
      'Katsina-Ala',
      'Vandeikya',
      'Adikpo',
      'Ukum',
      'Other Area',
    ],
    'Borno': [
      'Maiduguri (Capital)',
      'Biu',
      'Bama',
      'Monguno',
      'Gwoza',
      'Damboa',
      'Other Area',
    ],
    'Cross River': [
      'Calabar (Capital & GRA)',
      'Ikom',
      'Ogoja',
      'Ugep',
      'Akamkpa',
      'Obudu',
      'Akpabuyo',
      'Other Area',
    ],
    'Delta': [
      'Asaba (Capital & GRA)',
      'Warri',
      'Effurun',
      'Sapele',
      'Ughelli',
      'Agbor',
      'Oghara',
      'Kwale',
      'Ozoro',
      'Other Area',
    ],
    'Ebonyi': [
      'Abakaliki (Capital)',
      'Afikpo',
      'Onueke',
      'Edda',
      'Ishielu',
      'Ezza',
      'Other Area',
    ],
    'Edo': [
      'Benin City (GRA, Airport Rd)',
      'Benin City (Ugbowo, Ikpoba)',
      'Auchi',
      'Ekpoma',
      'Uromi',
      'Igarra',
      'Egor',
      'Ikpoba-Okha',
      'Other Area',
    ],
    'Ekiti': [
      'Ado-Ekiti (Capital & GRA)',
      'Ikere-Ekiti',
      'Ijero-Ekiti',
      'Oye-Ekiti',
      'Ikole-Ekiti',
      'Efon-Alaaye',
      'Aramoko-Ekiti',
      'Other Area',
    ],
    'Enugu': [
      'Enugu (Independence Layout)',
      'Enugu (GRA & New Haven)',
      'Enugu (Trans-Ekulu & Abakpa)',
      'Enugu (Achara Layout & Ogui)',
      'Nsukka',
      'Awgu',
      'Udi',
      'Oji River',
      'Other Area',
    ],
    'FCT (Abuja)': [
      'Maitama',
      'Asokoro',
      'Wuse II & Wuse Zone',
      'Garki I & Garki II',
      'Jabi & Utako',
      'Guzape & Asokoro Ext.',
      'Gwarinpa Estate',
      'Central Business District (CBD)',
      'Life Camp & Kado',
      'Lokogoma & Apo',
      'Lugbe (Airport Road)',
      'Kubwa',
      'Dawaki & Katampe',
      'Bwari & Dutse',
      'Kuje & Gwagwalada',
      'Other Area',
    ],
    'Gombe': [
      'Gombe (Capital)',
      'Kaltungo',
      'Billiri',
      'Bajoga',
      'Dukku',
      'Deba',
      'Other Area',
    ],
    'Imo': [
      'Owerri (Ikenegbu, Aladinma, GRA)',
      'Owerri (World Bank, New Owerri)',
      'Orlu',
      'Okigwe',
      'Mbaise',
      'Oguta',
      'Mbaitoli',
      'Other Area',
    ],
    'Jigawa': [
      'Dutse (Capital)',
      'Hadejia',
      'Kazaure',
      'Gumel',
      'Ringim',
      'Birnin Kudu',
      'Other Area',
    ],
    'Kaduna': [
      'Kaduna North (GRA, Malali, Ungwan Rimi)',
      'Kaduna South (Barnawa, Kakuri)',
      'Zaria (Samaru, Sabon Gari)',
      'Kafanchan',
      'Sabon Tasha & Millennium City',
      'Other Area',
    ],
    'Kano': [
      'Kano Municipal (GRA, Nassarawa)',
      'Fagge & Sabon Gari',
      'Dala & Gwale',
      'Tarauni & Gyadi-Gyadi',
      'Bompai & Commercial Area',
      'Wudil',
      'Other Area',
    ],
    'Katsina': [
      'Katsina (Capital)',
      'Daura',
      'Funtua',
      'Malumfashi',
      'Kankia',
      'Dutsin-Ma',
      'Other Area',
    ],
    'Kebbi': [
      'Birnin Kebbi (Capital)',
      'Argungu',
      'Yauri',
      'Zuru',
      'Jega',
      'Other Area',
    ],
    'Kogi': [
      'Lokoja (Capital & GRA)',
      'Okene',
      'Kabba',
      'Idah',
      'Anyigba',
      'Ajaokuta',
      'Ankpa',
      'Other Area',
    ],
    'Kwara': [
      'Ilorin (GRA, Fate Road, Challenge)',
      'Ilorin (Tanke, University Area)',
      'Offa',
      'Omu-Aran',
      'Jebba',
      'Lafiagi',
      'Other Area',
    ],
    'Lagos': [
      'Lekki Phase 1',
      'Victoria Island (VI)',
      'Ikoyi & Banana Island',
      'Lekki (Chevron, Agungi, Osapa)',
      'Ajah & Sangotedo',
      'Ibeju-Lekki & Epe',
      'Ikeja (GRA & Allen Avenue)',
      'Maryland & Anthony',
      'Surulere & Bode Thomas',
      'Yaba (Alagomeji, Akoka, Sabo)',
      'Magodo Phase 1 & 2',
      'Gbagada & Ogudu',
      'Festac Town & Amuwo-Odofin',
      'Ikorodu & Agric',
      'Alimosho (Egbeda, Igando, Ipaja)',
      'Ogba & Berger',
      'Agege & Abule Egba',
      'Oshodi & Isolo',
      'Apapa & Lagos Island',
      'Badagry',
      'Other Area',
    ],
    'Nasarawa': [
      'Lafia (Capital)',
      'Karu (Mararaba, Nyanya Axis)',
      'Keffi',
      'Akwanga',
      'Nasarawa Town',
      'Doma',
      'Other Area',
    ],
    'Niger': [
      'Minna (Capital & GRA)',
      'Suleja (Madalla, Zuma Rock Axis)',
      'Bida',
      'Kontagora',
      'Mokwa',
      'Lapai',
      'Other Area',
    ],
    'Ogun': [
      'Abeokuta (GRA, Ibara, Oke-Mosan)',
      'Ota / Canaanland / Sango',
      'Sagamu',
      'Ijebu-Ode',
      'Magboro, Mowe & Ibafo (Lagos Corridor)',
      'Arepo & Warewa',
      'Ilaro',
      'Agbera',
      'Other Area',
    ],
    'Ondo': [
      'Akure (Capital, Alagbaka, GRA)',
      'Ondo Town',
      'Owo',
      'Ikare-Akoko',
      'Ore',
      'Okitipupa',
      'Idanre',
      'Other Area',
    ],
    'Osun': [
      'Osogbo (Capital & GRA)',
      'Ile-Ife (OAU Campus & Town)',
      'Ilesa',
      'Ede',
      'Ikirun',
      'Iwo',
      'Ejigbo',
      'Other Area',
    ],
    'Oyo': [
      'Ibadan (Bodija, Agodi GRA, Jericho)',
      'Ibadan (Oluyole, Ring Road, Challenge)',
      'Ibadan (Dugbe, Mokola, UI / Samonda)',
      'Ibadan (Akobo, Kolapo Ishola)',
      'Ogbomoso',
      'Oyo Town',
      'Iseyin',
      'Saki',
      'Other Area',
    ],
    'Plateau': [
      'Jos (Rayfield, Millionaires Qtrs, GRA)',
      'Jos (Bukuru, Anglo Jos)',
      'Pankshin',
      'Shendam',
      'Barkin Ladi',
      'Mangu',
      'Other Area',
    ],
    'Rivers': [
      'Port Harcourt (Old GRA & New GRA)',
      'Port Harcourt (Trans Amadi & Peter Odili)',
      'Port Harcourt (Woji, Rumuola, D-Line)',
      'Port Harcourt (Ada George & Rumuokoro)',
      'Port Harcourt (Rumuodara & Eliozu)',
      'Obio-Akpor',
      'Eleme & Onne',
      'Bonny Island',
      'Oyigbo',
      'Other Area',
    ],
    'Sokoto': [
      'Sokoto (Capital & GRA)',
      'Wamakko',
      'Tambuwal',
      'Bodinga',
      'Gwadabawa',
      'Illela',
      'Other Area',
    ],
    'Taraba': [
      'Jalingo (Capital)',
      'Wukari',
      'Bali',
      'Gembu (Mambilla Plateau)',
      'Takum',
      'Sardauna',
      'Other Area',
    ],
    'Yobe': [
      'Damaturu (Capital)',
      'Potiskum',
      'Gashua',
      'Nguru',
      'Geidam',
      'Buni Yadi',
      'Other Area',
    ],
    'Zamfara': [
      'Gusau (Capital)',
      'Kaura Namoda',
      'Talata Mafara',
      'Anka',
      'Maru',
      'Bakura',
      'Other Area',
    ],
  };

  static List<String> getCitiesForState(String state) {
    return stateToCities[state] ?? ['Main City / District', 'Other Area'];
  }
}
